---
- name: Configuring the redos host
  hosts: redos
  gather_facts: no
  tasks:
    - name: Copy the enp0s3.nmconnection file
      copy:
        src: redos/enp0s3.nmconnection
        dest: /etc/NetworkManager/system-connections/enp0s3.nmconnection

    - name: Restart NetworkManager
      shell: systemctl restart NetworkManager

    - name: Install the iptables-services package
      dnf:
        name: iptables-services
        state: latest

    - name: Configure NAT
      shell: iptables -t nat -A POSTROUTING -s 192.168.1.0/29 -o enp0s8 -j MASQUERADE

    - name: Create the rules
      shell: iptables-save > /root/rules

    - name: Save the rules in crontab
      cron:
        name: "a job for reboot"
        special_time: reboot
        job: "/sbin/iptables-restore < /root/rules"

    - name: Enable crontab rules
      shell: crontab -e

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: true
        state: present
        reload: true

- name: Configuring the astra host
  hosts: astra
  gather_facts: no
  tasks:
    - name: Copy the /etc/network/interfaces file
      copy:
        src: astra/interfaces
        dest: /etc/network/interfaces

    - name: Restart networking
      shell: systemctl restart networking

    - name: Install the apache2 package
      apt:
        name: apache2
        state: latest

    - name: Copy the server.key file
      copy:
        src: astra/server.key
        dest: /etc/ssl/private/server.key

    - name: Copy the server.pem file
      copy:
        src: astra/server.pem
        dest: /etc/ssl/certs/server.pem

    - name: Copy the 000-default.conf file
      copy:
        src: astra/000-default.conf
        dest: /etc/apache2/sites-available/000-default.conf

    - name: Copy the default-ssl.conf file
      copy:
        src: astra/default-ssl.conf
        dest: /etc/apache2/sites-enabled/default-ssl.conf

    - name: Copy the html directory
      copy:
        src: astra/html
        dest: /var/www/

    - name: Reload apache2
      shell: systemctl reload apache2

    - name: Restart apache2
      shell: systemctl restart apache2

- name: Configuring the alt host
  hosts: alt
  gather_facts: no
  tasks:
    - name: Copy the /etc/net/ifaces/enp0s3/options file
      copy:
        src: alt/options
        dest: /etc/net/ifaces/enp0s3/options

    - name: Copy the /etc/net/ifaces/enp0s3/ipv4address file
      copy:
        src: alt/ipv4address
        dest: /etc/net/ifaces/enp0s3/ipv4address

    - name: Copy the /etc/net/ifaces/enp0s3/ipv4route file
      copy:
        src: alt/ipv4route
        dest: /etc/net/ifaces/enp0s3/ipv4route

    - name: Restart network
      shell: systemctl restart network
